[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[dependencies]
forge-std = "1.9.6"
solady = "0.1.14"
ExcessivelySafeCall = { version = "1.0.0", git = "https://github.com/nomad-xyz/ExcessivelySafeCall.git", rev = "81cd99ce3e69117d665d7601c330ea03b97acce0" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
