name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: 'read'
  actions: 'read'

jobs:
  # typecheck:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Setup
  #       uses: ./.github/actions/setup
  #     - name: Run TypeChecker
  #       run: |
  #         pnpm -r typecheck

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Setup
  #       uses: ./.github/actions/setup
  #     - name: Run Linters
  #       run: |
  #         pnpm -r lint

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Setup
  #       uses: ./.github/actions/setup
  #     - name: Run Tests
  #       run: |
  #         pnpm -r --filter '!e2e-test' test

  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
#         echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#         chmod 600 ~/.ssh/id_rsa
#       env:
#         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Write DEPLOYER_PRIVATE_KEY to .env
        run: echo "DEPLOYER_PRIVATE_KEY=${{ secrets.DEPLOYER_PRIVATE_KEY }}" >> packages/contracts/.env
      - name: Run Tests
        shell: bash
        run: |
          pnpm supersim &
          pnpm contracts:deploy:dev
  #         pnpm e2e-test:ci